# /k8s_deployments/demo_data_app_deployment.yaml
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app: demo-data-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-data-app
    spec:
      containers:
      - name: demo-data-app
        image: gcr.io/ats-beta-01-179603/demo-data-app
        imagePullPolicy: Always
        env:
          - name: ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: access-token-env
                key: ACCESS_TOKEN
          - name: ACCOUNT_ID
            valueFrom:
              secretKeyRef:
                name: account-id-env
                key: ACCOUNT_ID
            # NOTE: starting and ending times need to be in NY time
          - name: starting_time
            value: "2018-04-14T16:45:00"
          - name: ending_time
            value: "2018-04-14T16:55:30"
      volumes:
        - name: sv-1
          secret:
            secretName: access-token-env
        - name: sv-2
          secret:
            secretName: account-id-env

# $ python main.py -s "2018-04-15T19:38:30" -f "2018-04-15T19:39:00"
